//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Felhasznalo", Namespace="http://schemas.datacontract.org/2004/07/Server.Models")]
    public partial class Felhasznalo : ServiceReference1.Record
    {
        
        private bool AktivField;
        
        private string EmailField;
        
        private string HASHField;
        
        private byte JogField;
        
        private string LoginNevField;
        
        private string NevField;
        
        private string ProfilKepField;
        
        private string SALTField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Aktiv
        {
            get
            {
                return this.AktivField;
            }
            set
            {
                this.AktivField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HASH
        {
            get
            {
                return this.HASHField;
            }
            set
            {
                this.HASHField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte Jog
        {
            get
            {
                return this.JogField;
            }
            set
            {
                this.JogField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginNev
        {
            get
            {
                return this.LoginNevField;
            }
            set
            {
                this.LoginNevField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nev
        {
            get
            {
                return this.NevField;
            }
            set
            {
                this.NevField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProfilKep
        {
            get
            {
                return this.ProfilKepField;
            }
            set
            {
                this.ProfilKepField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SALT
        {
            get
            {
                return this.SALTField;
            }
            set
            {
                this.SALTField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Record", Namespace="http://schemas.datacontract.org/2004/07/Server.Models")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.Felhasznalo))]
    public partial class Record : object
    {
        
        private System.Nullable<int> IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelhasznalokService/FelhasznaloLista_CS", ReplyAction="http://tempuri.org/IFelhasznalokService/FelhasznaloLista_CSResponse")]
        ServiceReference1.Felhasznalo[] FelhasznaloLista_CS();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelhasznalokService/FelhasznaloLista_CS", ReplyAction="http://tempuri.org/IFelhasznalokService/FelhasznaloLista_CSResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Felhasznalo[]> FelhasznaloLista_CSAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelhasznalokService/FelhasznaloLista_Web", ReplyAction="http://tempuri.org/IFelhasznalokService/FelhasznaloLista_WebResponse")]
        ServiceReference1.Felhasznalo[] FelhasznaloLista_Web();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelhasznalokService/FelhasznaloLista_Web", ReplyAction="http://tempuri.org/IFelhasznalokService/FelhasznaloLista_WebResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Felhasznalo[]> FelhasznaloLista_WebAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelhasznalokService/FelhasznaloHozzaAd_CS", ReplyAction="http://tempuri.org/IFelhasznalokService/FelhasznaloHozzaAd_CSResponse")]
        string FelhasznaloHozzaAd_CS(ServiceReference1.Felhasznalo felhasznalo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelhasznalokService/FelhasznaloHozzaAd_CS", ReplyAction="http://tempuri.org/IFelhasznalokService/FelhasznaloHozzaAd_CSResponse")]
        System.Threading.Tasks.Task<string> FelhasznaloHozzaAd_CSAsync(ServiceReference1.Felhasznalo felhasznalo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelhasznalokService/FelhasznaloHozzaAd_Web", ReplyAction="http://tempuri.org/IFelhasznalokService/FelhasznaloHozzaAd_WebResponse")]
        string FelhasznaloHozzaAd_Web(ServiceReference1.Felhasznalo felhasznalo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelhasznalokService/FelhasznaloHozzaAd_Web", ReplyAction="http://tempuri.org/IFelhasznalokService/FelhasznaloHozzaAd_WebResponse")]
        System.Threading.Tasks.Task<string> FelhasznaloHozzaAd_WebAsync(ServiceReference1.Felhasznalo felhasznalo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelhasznalokService/FelhasznaloModosit_CS", ReplyAction="http://tempuri.org/IFelhasznalokService/FelhasznaloModosit_CSResponse")]
        string FelhasznaloModosit_CS(ServiceReference1.Felhasznalo felhasznalo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelhasznalokService/FelhasznaloModosit_CS", ReplyAction="http://tempuri.org/IFelhasznalokService/FelhasznaloModosit_CSResponse")]
        System.Threading.Tasks.Task<string> FelhasznaloModosit_CSAsync(ServiceReference1.Felhasznalo felhasznalo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelhasznalokService/FelhasznaloModosit_Web", ReplyAction="http://tempuri.org/IFelhasznalokService/FelhasznaloModosit_WebResponse")]
        string FelhasznaloModosit_Web(ServiceReference1.Felhasznalo felhasznalo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelhasznalokService/FelhasznaloModosit_Web", ReplyAction="http://tempuri.org/IFelhasznalokService/FelhasznaloModosit_WebResponse")]
        System.Threading.Tasks.Task<string> FelhasznaloModosit_WebAsync(ServiceReference1.Felhasznalo felhasznalo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelhasznalokService/FelhasznaloTorol_CS", ReplyAction="http://tempuri.org/IFelhasznalokService/FelhasznaloTorol_CSResponse")]
        string FelhasznaloTorol_CS(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelhasznalokService/FelhasznaloTorol_CS", ReplyAction="http://tempuri.org/IFelhasznalokService/FelhasznaloTorol_CSResponse")]
        System.Threading.Tasks.Task<string> FelhasznaloTorol_CSAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelhasznalokService/FelhasznaloTorol_Web", ReplyAction="http://tempuri.org/IFelhasznalokService/FelhasznaloTorol_WebResponse")]
        string FelhasznaloTorol_Web(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelhasznalokService/FelhasznaloTorol_Web", ReplyAction="http://tempuri.org/IFelhasznalokService/FelhasznaloTorol_WebResponse")]
        System.Threading.Tasks.Task<string> FelhasznaloTorol_WebAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IService1Channel : ServiceReference1.IService1, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ServiceReference1.IService1>, ServiceReference1.IService1
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1Client() : 
                base(Service1Client.GetDefaultBinding(), Service1Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService1.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), Service1Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ServiceReference1.Felhasznalo[] FelhasznaloLista_CS()
        {
            return base.Channel.FelhasznaloLista_CS();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Felhasznalo[]> FelhasznaloLista_CSAsync()
        {
            return base.Channel.FelhasznaloLista_CSAsync();
        }
        
        public ServiceReference1.Felhasznalo[] FelhasznaloLista_Web()
        {
            return base.Channel.FelhasznaloLista_Web();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Felhasznalo[]> FelhasznaloLista_WebAsync()
        {
            return base.Channel.FelhasznaloLista_WebAsync();
        }
        
        public string FelhasznaloHozzaAd_CS(ServiceReference1.Felhasznalo felhasznalo)
        {
            return base.Channel.FelhasznaloHozzaAd_CS(felhasznalo);
        }
        
        public System.Threading.Tasks.Task<string> FelhasznaloHozzaAd_CSAsync(ServiceReference1.Felhasznalo felhasznalo)
        {
            return base.Channel.FelhasznaloHozzaAd_CSAsync(felhasznalo);
        }
        
        public string FelhasznaloHozzaAd_Web(ServiceReference1.Felhasznalo felhasznalo)
        {
            return base.Channel.FelhasznaloHozzaAd_Web(felhasznalo);
        }
        
        public System.Threading.Tasks.Task<string> FelhasznaloHozzaAd_WebAsync(ServiceReference1.Felhasznalo felhasznalo)
        {
            return base.Channel.FelhasznaloHozzaAd_WebAsync(felhasznalo);
        }
        
        public string FelhasznaloModosit_CS(ServiceReference1.Felhasznalo felhasznalo)
        {
            return base.Channel.FelhasznaloModosit_CS(felhasznalo);
        }
        
        public System.Threading.Tasks.Task<string> FelhasznaloModosit_CSAsync(ServiceReference1.Felhasznalo felhasznalo)
        {
            return base.Channel.FelhasznaloModosit_CSAsync(felhasznalo);
        }
        
        public string FelhasznaloModosit_Web(ServiceReference1.Felhasznalo felhasznalo)
        {
            return base.Channel.FelhasznaloModosit_Web(felhasznalo);
        }
        
        public System.Threading.Tasks.Task<string> FelhasznaloModosit_WebAsync(ServiceReference1.Felhasznalo felhasznalo)
        {
            return base.Channel.FelhasznaloModosit_WebAsync(felhasznalo);
        }
        
        public string FelhasznaloTorol_CS(int id)
        {
            return base.Channel.FelhasznaloTorol_CS(id);
        }
        
        public System.Threading.Tasks.Task<string> FelhasznaloTorol_CSAsync(int id)
        {
            return base.Channel.FelhasznaloTorol_CSAsync(id);
        }
        
        public string FelhasznaloTorol_Web(int id)
        {
            return base.Channel.FelhasznaloTorol_Web(id);
        }
        
        public System.Threading.Tasks.Task<string> FelhasznaloTorol_WebAsync(int id)
        {
            return base.Channel.FelhasznaloTorol_WebAsync(id);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:3000/soap");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Service1Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Service1Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService1,
        }
    }
}
